name: publish
on: 
  push:
    branches:
      - main

jobs:
  publish-docker-image:
    name: publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker image
      run: |
         docker build . --tag ghcr.io/AxelZublena/nvim-in-docker:latest
         docker run ghcr.io/AxelZublena/nvim-in-docker:latest
         docker push ghcr.io/AxelZublena/nvim-in-docker:latest
